// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Data;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PostTag", b =>
                {
                    b.Property<int>("post_id")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.Property<int>("tag_id")
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    b.HasKey("post_id", "tag_id")
                        .HasName("PK__Post_Tag__4AFEED4D40095113");

                    b.HasIndex("tag_id");

                    b.ToTable("Post_Tag", (string)null);
                });

            modelBuilder.Entity("VocabGroup_Word", b =>
                {
                    b.Property<int>("group_id")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<int>("word_id")
                        .HasColumnType("int")
                        .HasColumnName("word_id");

                    b.HasKey("group_id", "word_id")
                        .HasName("PK__VocabGro__C2883474CEDF8177");

                    b.HasIndex("word_id");

                    b.ToTable("VocabGroup_Word", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("comment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("LikeNumber")
                        .HasColumnType("int")
                        .HasColumnName("like_number");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_comment_id");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("CommentId")
                        .HasName("PK__Comment__E7957687C296B01F");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.CommentLike", b =>
                {
                    b.Property<int>("CommentLikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("comment_like_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentLikeId"));

                    b.Property<int>("CommentId")
                        .HasColumnType("int")
                        .HasColumnName("comment_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("CommentLikeId")
                        .HasName("PK__CommentLike__CommentLikeId");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentLike", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.Exam", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("exam_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamId"));

                    b.Property<string>("BackgroundImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("background_image_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("ExamName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("exam_name");

                    b.Property<string>("ExamType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("exam_type");

                    b.HasKey("ExamId")
                        .HasName("PK__Exam__9C8C7BE95200C68D");

                    b.ToTable("Exam", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.ExamAttempt", b =>
                {
                    b.Property<long>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("attempt_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AttemptId"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("answer_text");

                    b.Property<int>("ExamId")
                        .HasColumnType("int")
                        .HasColumnName("exam_id");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("score");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("submitted_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("AttemptId")
                        .HasName("PK__ExamAtte__5621F94951E1EFD0");

                    b.HasIndex("ExamId");

                    b.HasIndex("UserId");

                    b.ToTable("ExamAttempt", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.Listening", b =>
                {
                    b.Property<int>("ListeningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("listening_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListeningId"));

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("correct_answer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<int>("ExamId")
                        .HasColumnType("int")
                        .HasColumnName("exam_id");

                    b.Property<string>("ListeningContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("listening_content");

                    b.Property<string>("ListeningQuestion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("listening_question");

                    b.Property<string>("ListeningType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("listening_type");

                    b.Property<string>("QuestionHtml")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question_html");

                    b.HasKey("ListeningId")
                        .HasName("PK__Listenin__91F7AA8D2027FE10");

                    b.HasIndex("ExamId");

                    b.ToTable("Listening", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<int?>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.Property<string>("Type")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__E059842F0D1EAED9");

                    b.HasIndex("UserId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit")
                        .HasColumnName("IsHidden");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("bit")
                        .HasColumnName("IsPinned");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RejectionReason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int?>("ViewCount")
                        .HasColumnType("int")
                        .HasColumnName("ViewCount");

                    b.HasKey("PostId")
                        .HasName("PK__Post__3ED787666EAF0D81");

                    b.HasIndex("UserId");

                    b.ToTable("Post", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.PostAttachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("attachment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("file_extension");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("file_type");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_url");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.HasKey("AttachmentId")
                        .HasName("PK__PostAttachment__AttachmentId");

                    b.HasIndex("PostId");

                    b.ToTable("PostAttachment", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.PostLike", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("PostId", "UserId")
                        .HasName("PK__PostLike__D54C641668B8C345");

                    b.HasIndex("UserId");

                    b.ToTable("PostLike", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.Reading", b =>
                {
                    b.Property<int>("ReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reading_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReadingId"));

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("correct_answer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<int>("ExamId")
                        .HasColumnType("int")
                        .HasColumnName("exam_id");

                    b.Property<string>("QuestionHtml")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question_html");

                    b.Property<string>("ReadingContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reading_content");

                    b.Property<string>("ReadingQuestion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reading_question");

                    b.Property<string>("ReadingType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("reading_type");

                    b.HasKey("ReadingId")
                        .HasName("PK__Reading__8091F95AEE19033B");

                    b.HasIndex("ExamId");

                    b.ToTable("Reading", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("report_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<int?>("CommentAuthorUserId")
                        .HasColumnType("int");

                    b.Property<int?>("CommentId")
                        .HasColumnType("int")
                        .HasColumnName("comment_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ReportId")
                        .HasName("PK__Report__779B7C589EC9B5E3");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId");

                    b.ToTable("Report", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.Speaking", b =>
                {
                    b.Property<int>("SpeakingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("speaking_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpeakingId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<int>("ExamId")
                        .HasColumnType("int")
                        .HasColumnName("exam_id");

                    b.Property<string>("SpeakingQuestion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("speaking_question");

                    b.Property<string>("SpeakingType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("speaking_type");

                    b.HasKey("SpeakingId")
                        .HasName("PK__Speaking__598C697384A5D6E1");

                    b.HasIndex("ExamId");

                    b.ToTable("Speaking", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.SpeakingAttempt", b =>
                {
                    b.Property<long>("SpeakingAttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("speaking_attempt_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SpeakingAttemptId"));

                    b.Property<long>("AttemptId")
                        .HasColumnType("bigint")
                        .HasColumnName("attempt_id");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("audio_url");

                    b.Property<int>("SpeakingId")
                        .HasColumnType("int")
                        .HasColumnName("speaking_id");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("submitted_at");

                    b.Property<string>("Transcript")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("transcript");

                    b.HasKey("SpeakingAttemptId")
                        .HasName("PK__SpeakingAttempt");

                    b.HasIndex("AttemptId");

                    b.HasIndex("SpeakingId");

                    b.ToTable("SpeakingAttempt", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.SpeakingFeedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("feedback_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("AiAnalysisJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ai_analysis_json");

                    b.Property<decimal?>("Coherence")
                        .HasColumnType("decimal(3, 1)")
                        .HasColumnName("coherence");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<decimal?>("Fluency")
                        .HasColumnType("decimal(3, 1)")
                        .HasColumnName("fluency");

                    b.Property<decimal?>("GrammarAccuracy")
                        .HasColumnType("decimal(3, 1)")
                        .HasColumnName("grammar_accuracy");

                    b.Property<decimal?>("LexicalResource")
                        .HasColumnType("decimal(3, 1)")
                        .HasColumnName("lexical_resource");

                    b.Property<decimal?>("Overall")
                        .HasColumnType("decimal(3, 1)")
                        .HasColumnName("overall");

                    b.Property<decimal?>("Pronunciation")
                        .HasColumnType("decimal(3, 1)")
                        .HasColumnName("pronunciation");

                    b.Property<long>("SpeakingAttemptId")
                        .HasColumnType("bigint")
                        .HasColumnName("speaking_attempt_id");

                    b.HasKey("FeedbackId")
                        .HasName("PK__Speaking__7A6B2B8CED144F63");

                    b.HasIndex("SpeakingAttemptId");

                    b.ToTable("SpeakingFeedback", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tag_name");

                    b.HasKey("TagId")
                        .HasName("PK__Tag__4296A2B65970D7BC");

                    b.HasIndex(new[] { "TagName" }, "UQ__Tag__E298655CA5EF38BD")
                        .IsUnique();

                    b.ToTable("Tag", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasDefaultValue("VND")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("payment_method");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    b.Property<string>("ProviderTxnId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("provider_txn_id");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("VIP")
                        .HasColumnName("purpose");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("TransactionId")
                        .HasName("PK__Transact__85C600AF72F38544");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PlanId");

                    b.HasIndex("ProviderTxnId")
                        .IsUnique()
                        .HasFilter("[provider_txn_id] IS NOT NULL");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_Transaction_Status_CreatedAt");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("IX_Transaction_User_CreatedAt");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Firstname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("firstname");

                    b.Property<bool>("IsRestricted")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("lastname");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varbinary(256)")
                        .HasColumnName("password_hash");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varbinary(128)")
                        .HasColumnName("password_salt");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("user")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.Property<DateTime?>("VipExpireAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("vip_expire_at");

                    b.HasKey("UserId")
                        .HasName("PK__Users__B9BE370F8208A11F");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__AB6E616418A9BBE3")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "UQ__Users__F3DBC572977AB95F")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.UserPostHide", b =>
                {
                    b.Property<int>("UserPostHideId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_post_hide_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserPostHideId"));

                    b.Property<DateTime>("HiddenAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("hidden_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("UserPostHideId")
                        .HasName("PK__UserPostH__user_post_hide_id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPostHide", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.UserSignInHistory", b =>
                {
                    b.Property<int>("SigninId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("signin_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SigninId"));

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("device_info");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("location");

                    b.Property<DateTime>("SignedInAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("signed_in_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("SigninId")
                        .HasName("PK__UserSignInHistory__SignInId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSignInHistory", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.VipPlan", b =>
                {
                    b.Property<int>("VipPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VipPlanId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int")
                        .HasColumnName("duration_days");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("plan_name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.HasKey("VipPlanId")
                        .HasName("PK_VipPlans");

                    b.ToTable("VipPlans", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.VocabGroup", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Groupname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("groupname");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("GroupId")
                        .HasName("PK__VocabGro__D57795A0AB20D47E");

                    b.HasIndex(new[] { "UserId", "Groupname" }, "UX_group_user")
                        .IsUnique();

                    b.ToTable("VocabGroup", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.Word", b =>
                {
                    b.Property<int>("WordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("word_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WordId"));

                    b.Property<string>("Audio")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("audio");

                    b.Property<string>("Example")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("example");

                    b.Property<string>("Meaning")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("meaning");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("word");

                    b.HasKey("WordId")
                        .HasName("PK__Word__7FFA1D4039C4B1A6");

                    b.ToTable("Word", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.Writing", b =>
                {
                    b.Property<int>("WritingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("writing_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WritingId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<int>("ExamId")
                        .HasColumnType("int")
                        .HasColumnName("exam_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ImageUrl");

                    b.Property<string>("WritingQuestion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("writing_question");

                    b.HasKey("WritingId")
                        .HasName("PK__Writing__4AE2633E2FDA5C2C");

                    b.HasIndex("ExamId");

                    b.ToTable("Writing", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.WritingFeedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("feedback_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<long>("AttemptId")
                        .HasColumnType("bigint")
                        .HasColumnName("attempt_id");

                    b.Property<decimal?>("CoherenceCohesion")
                        .HasColumnType("decimal(3, 1)")
                        .HasColumnName("coherence_cohesion");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("FeedbackSections")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("feedback_sections");

                    b.Property<decimal?>("GrammarAccuracy")
                        .HasColumnType("decimal(3, 1)")
                        .HasColumnName("grammar_accuracy");

                    b.Property<string>("GrammarVocabJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("grammar_vocab_json");

                    b.Property<decimal?>("LexicalResource")
                        .HasColumnType("decimal(3, 1)")
                        .HasColumnName("lexical_resource");

                    b.Property<decimal?>("Overall")
                        .HasColumnType("decimal(3, 1)")
                        .HasColumnName("overall");

                    b.Property<decimal?>("TaskAchievement")
                        .HasColumnType("decimal(3, 1)")
                        .HasColumnName("task_achievement");

                    b.Property<int>("WritingId")
                        .HasColumnType("int")
                        .HasColumnName("writing_id");

                    b.HasKey("FeedbackId")
                        .HasName("PK__WritingF__7A6B2B8C940C0650");

                    b.HasIndex("AttemptId");

                    b.HasIndex("WritingId");

                    b.ToTable("WritingFeedback", (string)null);
                });

            modelBuilder.Entity("PostTag", b =>
                {
                    b.HasOne("WebAPI.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("post_id")
                        .IsRequired()
                        .HasConstraintName("FK__Post_Tag__post_i__7F2BE32F");

                    b.HasOne("WebAPI.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("tag_id")
                        .IsRequired()
                        .HasConstraintName("FK__Post_Tag__tag_id__00200768");
                });

            modelBuilder.Entity("VocabGroup_Word", b =>
                {
                    b.HasOne("WebAPI.Models.VocabGroup", null)
                        .WithMany()
                        .HasForeignKey("group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__VocabGrou__group__5CD6CB2B");

                    b.HasOne("WebAPI.Models.Word", null)
                        .WithMany()
                        .HasForeignKey("word_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__VocabGrou__word___5DCAEF64");
                });

            modelBuilder.Entity("WebAPI.Models.Comment", b =>
                {
                    b.HasOne("WebAPI.Models.Comment", "ParentComment")
                        .WithMany("InverseParentComment")
                        .HasForeignKey("ParentCommentId")
                        .HasConstraintName("FK__Comment__parent___778AC167");

                    b.HasOne("WebAPI.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK__Comment__post_id__75A278F5");

                    b.HasOne("WebAPI.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Comment__user_id__76969D2E");

                    b.Navigation("ParentComment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebAPI.Models.CommentLike", b =>
                {
                    b.HasOne("WebAPI.Models.Comment", "Comment")
                        .WithMany("CommentLikes")
                        .HasForeignKey("CommentId")
                        .IsRequired()
                        .HasConstraintName("FK__CommentLike__comment_id");

                    b.HasOne("WebAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__CommentLike__user_id");

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebAPI.Models.ExamAttempt", b =>
                {
                    b.HasOne("WebAPI.Models.Exam", "Exam")
                        .WithMany("ExamAttempts")
                        .HasForeignKey("ExamId")
                        .IsRequired()
                        .HasConstraintName("FK__ExamAttem__exam___534D60F1");

                    b.HasOne("WebAPI.Models.User", "User")
                        .WithMany("ExamAttempts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__ExamAttem__user___5441852A");

                    b.Navigation("Exam");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebAPI.Models.Listening", b =>
                {
                    b.HasOne("WebAPI.Models.Exam", "Exam")
                        .WithMany("Listenings")
                        .HasForeignKey("ExamId")
                        .IsRequired()
                        .HasConstraintName("FK__Listening__exam___5BE2A6F2");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("WebAPI.Models.Notification", b =>
                {
                    b.HasOne("WebAPI.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__user___6D0D32F4");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebAPI.Models.Post", b =>
                {
                    b.HasOne("WebAPI.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Post__user_id__71D1E811");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebAPI.Models.PostAttachment", b =>
                {
                    b.HasOne("WebAPI.Models.Post", "Post")
                        .WithMany("Attachments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__PostAttachment__post_id");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("WebAPI.Models.PostLike", b =>
                {
                    b.HasOne("WebAPI.Models.Post", "Post")
                        .WithMany("PostLikes")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK__PostLike__post_i__02FC7413");

                    b.HasOne("WebAPI.Models.User", "User")
                        .WithMany("PostLikes")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__PostLike__user_i__03F0984C");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebAPI.Models.Reading", b =>
                {
                    b.HasOne("WebAPI.Models.Exam", "Exam")
                        .WithMany("Readings")
                        .HasForeignKey("ExamId")
                        .IsRequired()
                        .HasConstraintName("FK__Reading__exam_id__5812160E");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("WebAPI.Models.Report", b =>
                {
                    b.HasOne("WebAPI.Models.Comment", "Comment")
                        .WithMany("Reports")
                        .HasForeignKey("CommentId")
                        .HasConstraintName("FK_Report_Comment");

                    b.HasOne("WebAPI.Models.User", "User")
                        .WithMany("Reports")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Report__user_id__60A75C0F");

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebAPI.Models.Speaking", b =>
                {
                    b.HasOne("WebAPI.Models.Exam", "Exam")
                        .WithMany("Speakings")
                        .HasForeignKey("ExamId")
                        .IsRequired()
                        .HasConstraintName("FK__Speaking__exam_i__6383C8BA");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("WebAPI.Models.SpeakingAttempt", b =>
                {
                    b.HasOne("WebAPI.Models.ExamAttempt", "ExamAttempt")
                        .WithMany()
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SpeakingAttempt_ExamAttempt");

                    b.HasOne("WebAPI.Models.Speaking", "Speaking")
                        .WithMany()
                        .HasForeignKey("SpeakingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SpeakingAttempt_Speaking");

                    b.Navigation("ExamAttempt");

                    b.Navigation("Speaking");
                });

            modelBuilder.Entity("WebAPI.Models.SpeakingFeedback", b =>
                {
                    b.HasOne("WebAPI.Models.SpeakingAttempt", "SpeakingAttempt")
                        .WithMany()
                        .HasForeignKey("SpeakingAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpeakingAttempt");
                });

            modelBuilder.Entity("WebAPI.Models.Transaction", b =>
                {
                    b.HasOne("WebAPI.Models.VipPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Transactions_VipPlans");

                    b.HasOne("WebAPI.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Transacti__user___656C112C");

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebAPI.Models.UserPostHide", b =>
                {
                    b.HasOne("WebAPI.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UserPostHide__post_id");

                    b.HasOne("WebAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UserPostHide__user_id");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebAPI.Models.UserSignInHistory", b =>
                {
                    b.HasOne("WebAPI.Models.User", "User")
                        .WithMany("SignInHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserSignInHistory_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebAPI.Models.VocabGroup", b =>
                {
                    b.HasOne("WebAPI.Models.User", null)
                        .WithMany("VocabGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebAPI.Models.Writing", b =>
                {
                    b.HasOne("WebAPI.Models.Exam", "Exam")
                        .WithMany("Writings")
                        .HasForeignKey("ExamId")
                        .IsRequired()
                        .HasConstraintName("FK__Writing__exam_id__5FB337D6");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("WebAPI.Models.WritingFeedback", b =>
                {
                    b.HasOne("WebAPI.Models.ExamAttempt", "ExamAttempt")
                        .WithMany()
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Models.Writing", "Writing")
                        .WithMany()
                        .HasForeignKey("WritingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamAttempt");

                    b.Navigation("Writing");
                });

            modelBuilder.Entity("WebAPI.Models.Comment", b =>
                {
                    b.Navigation("CommentLikes");

                    b.Navigation("InverseParentComment");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("WebAPI.Models.Exam", b =>
                {
                    b.Navigation("ExamAttempts");

                    b.Navigation("Listenings");

                    b.Navigation("Readings");

                    b.Navigation("Speakings");

                    b.Navigation("Writings");
                });

            modelBuilder.Entity("WebAPI.Models.Post", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Comments");

                    b.Navigation("PostLikes");
                });

            modelBuilder.Entity("WebAPI.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ExamAttempts");

                    b.Navigation("Notifications");

                    b.Navigation("PostLikes");

                    b.Navigation("Posts");

                    b.Navigation("Reports");

                    b.Navigation("SignInHistories");

                    b.Navigation("Transactions");

                    b.Navigation("VocabGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
